wiki/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles
  root 'articles#index'
end

wiki/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

wiki/app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

wiki/app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

wiki/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

wiki/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

wiki/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /articles
  # GET /articles.json
  def index
    if params[:category].blank?
      @articles = Article.all.order('created_at DESC')
    else
      @category_id = Category.find_by(name: params[:category]).id
      @articles = Article.where(category_id: @category_id).order('created_at DESC')
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show; end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit; end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :content, :category_id)
  end
end

wiki/app/helpers/application_helper.rb
module ApplicationHelper
end

wiki/app/helpers/articles_helper.rb
module ArticlesHelper
end

wiki/app/views/articles/_form.html.haml
= simple_form_for(@article) do |f|
  = f.collection_select :category_id, Category.all, :id, :name, {promt: 'Choose a Category'}
  = f.input :title
  = f.input :content
  = f.button :submit

wiki/app/views/articles/edit.html.haml
%h1 Editing Article

= render 'form', article: @article

= link_to 'Show', @article
= link_to 'Back', articles_path

wiki/app/views/articles/index.html.haml
%h1 Articles

- @articles.each do |article|
  %h2= article.title
  %p
    Published at
    = article.created_at.strftime('%b %d, %Y')
  %p= truncate(article.content, length: 200)
- if user_signed_in?
  = link_to 'New Article', new_article_path

wiki/app/views/articles/new.html.haml
%h1 New Article

= render 'form', article: @article

= link_to 'Back', articles_path

wiki/app/views/articles/show.html.haml
%h1= @article.title
%p= @article.content

= link_to "Back", root_path
= link_to 'Edit', edit_article_path(@article)
= link_to 'Delete', article_path(@article), method: :delete#, data: { confirm: "Are you sure ?" }

wiki/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Wiki
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    -#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert

    = yield

    %ul
      %li= link_to "All Articles", root_path
      - Category.all.each do |category|
        %li= link_to category.name, articles_path(category: category.name)